import type { RestaurantFilterCategory } from './restaurant'

export interface CategoryRegressionFixture {
  source: 'good-price' | 'incheon-smart-food'
  id: string
  kakaoPlaceId: string
  name: string
  menuNames: string[]
  expectedCategory: RestaurantFilterCategory
}

export const CATEGORY_REGRESSION_FIXTURES: readonly CategoryRegressionFixture[] = [
  {
    source: 'good-price',
    id: 'aa32471dcaf74a180177',
    kakaoPlaceId: '1525689156',
    name: '샐러드하우스',
    menuNames: ['에그듬뿍샌드위치', '그린샐러드', '닭가슴살샐러드'],
    expectedCategory: '샐러드·브런치',
  },
  {
    source: 'good-price',
    id: '07e0943d8210ff09212d',
    kakaoPlaceId: '16795631',
    name: '삼삼치킨',
    menuNames: ['치킨', '양념치킨', '간장치킨'],
    expectedCategory: '치킨·피자',
  },
  {
    source: 'good-price',
    id: '68746ac37af1cb5f859e',
    kakaoPlaceId: '20745240',
    name: '개봉분식',
    menuNames: ['떡볶이', '김밥', '라면'],
    expectedCategory: '분식·간편식',
  },
  {
    source: 'good-price',
    id: 'e979a2f9ef774301524c',
    kakaoPlaceId: '1614141978',
    name: '미인브레드 호암로점',
    menuNames: ['단팥빵', '버터크림빵', '버터소금빵', '소세지피자'],
    expectedCategory: '베이커리·디저트',
  },
  {
    source: 'good-price',
    id: '3388201d8620b15b898b',
    kakaoPlaceId: '484247724',
    name: '롬누',
    menuNames: ['차돌양지쌀국수'],
    expectedCategory: '아시아음식',
  },
  {
    source: 'good-price',
    id: '513c4a461c8788a5708b',
    kakaoPlaceId: '1248296422',
    name: '한담',
    menuNames: ['옛날즉석우동', '수제카레덮밥', '카레우동'],
    expectedCategory: '일식',
  },
  {
    source: 'good-price',
    id: '1b9b8293c985b2e89bcb',
    kakaoPlaceId: '1337635251',
    name: '황소포차',
    menuNames: ['계란말이'],
    expectedCategory: '주점·안주',
  },
  {
    source: 'good-price',
    id: '72b9d4a333e8a166e22c',
    kakaoPlaceId: '15823017',
    name: '신가네 숯불꼼장어',
    menuNames: ['숯불꼼장어 2인'],
    expectedCategory: '해산물·회',
  },
  {
    source: 'good-price',
    id: 'bbd9558b060ff68540a2',
    kakaoPlaceId: '1934206295',
    name: '직화구이 인생맛집',
    menuNames: ['뚝배기불고기', '청국장', '제육직화'],
    expectedCategory: '고기·구이',
  },
  {
    source: 'good-price',
    id: '5291d3bc1ae026059cdf',
    kakaoPlaceId: '1712737798',
    name: '또부리또',
    menuNames: ['포크부리또', '치킨부리또', '비프부리또'],
    expectedCategory: '분식·간편식',
  },
  {
    source: 'good-price',
    id: '8cf6e591e06c714da34c',
    kakaoPlaceId: '1082291086',
    name: '마라양꼬치',
    menuNames: ['생양꼬치', '양갈비(340g)'],
    expectedCategory: '아시아음식',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-156109',
    kakaoPlaceId: '14589561',
    name: '보타닉 하우스',
    menuNames: ['아메리카노', '샌드위치', '과일 스무디와 에이드'],
    expectedCategory: '샐러드·브런치',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-161690',
    kakaoPlaceId: '21317904',
    name: '꼬꼬네 닭강정',
    menuNames: ['후라이드치킨', '양념치킨', '닭강정', '골뱅이'],
    expectedCategory: '치킨·피자',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-163285',
    kakaoPlaceId: '8117520',
    name: '파리바게뜨 부평롯데점',
    menuNames: ['정품 크라상', '소시지가 맛있는 핫도그', '뜯어먹는 고구마 데니쉬'],
    expectedCategory: '베이커리·디저트',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-182215',
    kakaoPlaceId: '20644715',
    name: '뚜레쥬르 산곡푸르지오점',
    menuNames: ['플레인 베이글', '에그마요 산도', '햄치즈 페스츄리 샌드위치'],
    expectedCategory: '베이커리·디저트',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-154369',
    kakaoPlaceId: '26644235',
    name: '설빙 인천계양구청점',
    menuNames: ['찹쌀 핫도그', '인절미토스트', '인절미설빙'],
    expectedCategory: '베이커리·디저트',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-22540',
    kakaoPlaceId: '27300338',
    name: '드마리스 청라점',
    menuNames: ['뷔페(유아)', '뷔페(소인)', '뷔페(평일/성인/점심)'],
    expectedCategory: '뷔페',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-175013',
    kakaoPlaceId: '27270667',
    name: '스와갓인디아레스토랑',
    menuNames: ['바드사히 치킨 커리', '치킨 티카 마살라', '치킨 마카니'],
    expectedCategory: '아시아음식',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-175151',
    kakaoPlaceId: '21568933',
    name: '포베이 인천스퀘어원직영점',
    menuNames: ['칠리치킨 프라이드', '비프쌀국수', '해산물 팟타이'],
    expectedCategory: '아시아음식',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-180472',
    kakaoPlaceId: '12132209',
    name: '올드사이공',
    menuNames: ['양지 쌀국수', '숯불돼지고기 덮밥', '월남쌈'],
    expectedCategory: '아시아음식',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-158655',
    kakaoPlaceId: '811499416',
    name: '호주가',
    menuNames: ['IPA', '모카스타우트', '엠버복'],
    expectedCategory: '주점·안주',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-158880',
    kakaoPlaceId: '1183405825',
    name: '주가네포차',
    menuNames: ['꼬치오뎅탕', '해물파전', '골뱅이', '모듬전'],
    expectedCategory: '주점·안주',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-930889',
    kakaoPlaceId: '10289623',
    name: '동해을지로골뱅이',
    menuNames: ['계란말이(샐러드 포함)', '오뎅탕', '을지로골뱅이 단품'],
    expectedCategory: '해산물·회',
  },
  {
    source: 'incheon-smart-food',
    id: 'incheon-922521',
    kakaoPlaceId: '11943614',
    name: '황소고집돌곱창',
    menuNames: ['볶음밥', '소곱창구이', '소대창구이', '소막창구이'],
    expectedCategory: '고기·구이',
  },
]
